### ISSUE TITLE
Readonly overlay images

### ISSUE THREAD

**Issue by NanoNabla** [apptainer/apptainer-userdocs#133]
Using Apptainer with `--overlay ` on an MPI applications I got into the issue that apptainer is not able to start more than one instance with overlay reasonably.
I took a look into the userdocs but couldn't find any hint how to make overlay images mounted in read-only mode to get rid of this issue. Then I found the solution in apptainer/singularity#5577 to use `--overlay overlay.img:ro`.

Is using `:ro`  a feature you do not want to support officially or is it simply missing in the user docs?
If it simply missing I can do a PR if I am aked for.

**Comment by DrDaveD** [comment]
It is in the user docs at https://apptainer.org/docs/user/main/persistent_overlays.html#readonly-overlay.  Perhaps you just missed it?

**Comment by DrDaveD** [comment]
I think it could be good to add to the [overlay option help message](https://github.com/apptainer/apptainer/blob/main/cmd/internal/cli/action_flags.go#L152) that you can append `:ro` to the image name.  Would you like to make that PR?  I'm thinking changing "or as read-only" to "or, if ':ro' is appended to the image, as read-only".

**Comment by NanoNabla** [comment]
> It is in the user docs at https://apptainer.org/docs/user/main/persistent_overlays.html#readonly-overlay. Perhaps you just missed it?

It seems to been added in da87030. Sorry, I had to task to start this issue for some month on my desk but didn't have the time... Today, I just took a short look into https://apptainer.org/docs/user/main/persistent_overlays.html#readonly-overlay to see if it is a current issue and overlooked it somehow. 
From my point this issue can be closed since it is not a current topic anymore




> I think it could be good to add to the [overlay option help message](https://github.com/apptainer/apptainer/blob/main/cmd/internal/cli/action_flags.go#L152) that you can append `:ro` to the image name. Would you like to make that PR? I'm thinking changing "or as read-only" to "or, if ':ro' is appended to the image, as read-only".

Seems to be a good idea. I did took a look into singularity code yet but I can try to achieve this.

**Comment by DrDaveD** [comment]
Yes, it was a relatively recent addition, I had forgotten.   Closing this one.
