### ISSUE TITLE
overlay documentation is wrong

### ISSUE THREAD

**Issue by surak** [apptainer/apptainer-userdocs#135]
## Which Document page:

On what page is the problem?

https://apptainer.org/docs/user/main/persistent_overlays.html

or

https://github.com/apptainer/apptainer-userdocs/blob/main/persistent_overlays.rst

### Expected results:

I would like to use overlay, but if I copy line 104, check the actual results. This is with `apptainer version 1.0.3-1.el8` 

### Actual results:

```
apptainer overlay create --fakeroot --size 1024 overlay.img
Error for command "create": unknown flag: --fakeroot

Options for create command:

      --create-dir strings   directory to create as part of the overlay layout
  -h, --help                 help for create
  -s, --size int             size of the EXT3 writable overlay in MiB (default 64)

Run 'apptainer --help' for more detailed usage information.
```

**Comment by DrDaveD** [comment]
You're looking at the most recent documentation, which has changed since apptainer 1.0.  For apptainer 1.0 you need to look under https://apptainer.org/docs/user/1.0.
