### ISSUE TITLE
[quick_start] INSTALL.md link is broken?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [apptainer/apptainer-userdocs#139]
## Which Document page:

https://apptainer.org/docs/user/1.1/quick_start.html

### Expected results:

I'd expect to see it link to
https://github.com/apptainer/apptainer/blob/release-1.1/INSTALL.md

### Actual results:

By means of this code:
https://github.com/apptainer/apptainer-userdocs/blob/597561c1aafa7ac8aca6aa338f3b39eba0c32a70/quick_start.rst#L28-L30

It actually links to
https://github.com/apptainer/apptainer/blob/1.1/INSTALL.md
But that page (branch) does not exist

I notice that this repo uses `1.0`, `1.1` for branch names - maybe it should use same convention, `release-1.0`, `release-1.1`?

While updating automated / narrowly scoped scripts
https://github.com/EricCousineau-TRI/repro/commit/f50c60dad7e8477499fa0591e74121eb62607232

**Comment by DrDaveD** [comment]
Thanks for the report.  Fixed by #140.

**Comment by DrDaveD** [comment]
Yes the branch names are different in the docs.  I don't think it's worth changing them though.
