### ISSUE TITLE
Replace references of singularity in CLI examples

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/apptainer-userdocs#17]
The codeblocks used inside this project do not use a search and replace strategy at generation time like `{Singularity}` provides, rename the application name in CLI examples.

**Comment by DrDaveD** [comment]
Do please look first to see if could use a substitution in the code blocks, like {command}, for example, because that could facilitate easier sharing of documentation.  I wouldn't be surprised though if it can't be done in code blocks.

**Comment by DrDaveD** [comment]
I verified in #39 that those substitutions (specified in replacements.py) can work in code blocks, so replace everything referring to the `singularity` command with `{command}` and set its value to `apptainer` in replacements.py.
