### ISSUE TITLE
Add note on setuid mode and apptainer instance list

### ISSUE THREAD

**Issue by philippfriese** [apptainer/apptainer-userdocs#203]
## Which Document page:

Apptainer User Guide - Instances - Running Services - [Starting Instances](https://apptainer.org/docs/user/main/running_services.html#starting-instances)

### Expected results:

A note about requiring root on `apptainer instance list` if in setuid mode.

### Actual results:

If apptainer is used in setuid mode, then instances, although started by $USER, are managed by root. Hence `apptainer instance list` will show an empty list. The current note on the document page linked above informs that: 
> "[...] if you use `sudo` to start an instance as `root`, you will need to use `sudo` for all commands managing that instance". 

An additional note informing about the same requirement for `setuid` mode might help avoid confusion.

**Comment by DrDaveD** [comment]
Do you mean that an unprivileged user that starts an instance with a setuid-installation of apptainer will not be able to list the instances with an unprivileged installation of apptainer?  That's not what I see when I try it. 

I believe the reason for the distinction regarding root in the current documentation is that instance information is stored in $HOME, and running sudo changes $HOME to ~root.

**Comment by philippfriese** [comment]
That's interesting! I did some more testing and indeed, the following works:

```bash
$ apptainer instance start app.sif app_instance
INFO:    instance started successfully

$ apptainer instance list
INSTANCE NAME    PID     IP    IMAGE
app_instance     8705          /path/to/app.sif
```

However, my use-case necessitates the `--net` flag: 

```bash
$ apptainer instance start --net app.sif app_instance
INFO:    instance started successfully

$ apptainer instance list
INSTANCE NAME    PID     IP    IMAGE

$ sudo apptainer instance list
INSTANCE NAME    PID     IP           IMAGE
app_instance     9757    10.22.0.4    /path/to/app.sif
```

Looking at top, the parent process `Apptainer instance: pfriese [app_instance]` is owned by my user `pfriese` in the first case and by `root` in the second. 
The [Network virtualization](https://apptainer.org/docs/user/main/networking.html) documentation page mentions that these features are restricted to `root`, which would explain why launching it as an unprivileged user succeeds in setuid-mode and yields the observed behaviour.

**Comment by DrDaveD** [comment]
I don't see that behavior when I try it; I get an error when I try `instance start --net` saying that it is a privileged operation.  Please instead create an issue at https://github.com/apptainer/apptainer along with complete instructions on how to reproduce it.  I don't think that behavior is correct.

Even if I add myself to `allow net users` and add `bridge` to `allow net networks` which allows me to start such an instance, the instance is still owned by me.  That was with apptainer-1.1.9 on el7.
