### ISSUE TITLE
Remove references to singularity versions

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer-userdocs#3]
In order to greatly simplify the task of renaming to Apptainer, first remove all references to specific version numbers in this repository.  Remove descriptions of older behavior, and for anything that describes behavior starting at a certain version number such as "Since version 3.6 ..." just remove that reference while leaving the rest of the behavior description because it still applies to the current version.  Only leave the description of the current behavior; people who want to know the older behavior can look at the archived versions of the documentation.

**Comment by pedroalvesbatista** [comment]
Alright, working on it.
