### ISSUE TITLE
Update references and config statements in conf.py

### ISSUE THREAD

**Issue by pedroalvesbatista** [apptainer/apptainer-userdocs#30]

**Comment by pedroalvesbatista** [comment]
This file has a bunch of references to HPCng and Singularity in some variables.

**Comment by DrDaveD** [comment]
At the same time, even though there are already github variable specifications in conf.py (`github_user`, `github_repo`, `github_version`), I don't think they're usable in .rst sources.  So in addition, make at least one other variable in replacements.py `{orgrepo}` that is set to the value `apptainer/apptainer` and use it wherever there are now references to `github.com` followed by `apptainer/apptainer`, `sylabs/singularity`, or `hpcng/singularity`.
