### ISSUE TITLE
Sylabs originated content vs LICENSE copyright years

### ISSUE THREAD

**Issue by dtrudg** [apptainer/apptainer-userdocs#34]
Hi all,

You have been bringing in some 2021 changes from the Sylabs documentation repositories, e.g. https://github.com/apptainer/apptainer-userdocs/pull/33

Your LICENSE file is only listing copyright for Sylabs up to 2020, not 2021.

Please could you ensure on admindocs and userdocs that the copyright attribution matches the years for which you have brought content over from the Sylabs repositories.

Thanks!

**Comment by DrDaveD** [comment]
Thanks for pointing that out.  Generally we try to pull in any copyright year changes that are included in the Sylabs PRs, but it turns out we skipped the whole PR where that change was made.  We should have included just the Copyright update.
