### ISSUE TITLE
Use {ENVPREFIX} instead of APPTAINER for environment variables

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer-userdocs#47]
Replace the `APPTAINER` prefixes introduced in #22 with a new replacement variable `{ENVPREFIX}`.

**Comment by pedroalvesbatista** [comment]
Would `{ENVPREFIX}` go in `replacements.py` ?

**Comment by DrDaveD** [comment]
I am reopening this, because I still see a lot of occurrences of APPTAINER in this repository.
