### ISSUE TITLE
Re-enable publishing to the website

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer-userdocs#6]
In pr #1, publishing from this repository was disabled.  Re-enable it such that the documentation is pushed to https://apptainer.org/docs/user (i.e., not to https://aptainer.org/user-docs since that is written by https://github.com/apptainer/singularity-userdocs).

**Comment by brianclemens** [comment]
Fixed in #8 
Will work with @ressonix to make those accessible on apptainer.org
