### ISSUE TITLE
Remove references to "library" (and "shub"?)

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer-userdocs#70]
## Which Document page:

https://apptainer.org/docs/user/main/build_a_container.html?highlight=library

### Expected results:

The apptainer user docs refer to the "library" container resource, which I understand to have been removed from apptainer. (The "shub" resource might also be removed.)

### Actual results:

```
$ apptainer --version
apptainer version 1.0.0~rc.2-1.fc35

$ apptainer pull library://library/default/rockylinux
FATAL:   Unable to get library client configuration: remote has no library client
```

**Comment by ikaneshiro** [comment]
Hi @anderbubble, `library` still exists but the defaults have been changed and `shub` is in a read only archive state so we should take additional note of these changes in the docs. I will submit a PR with fixes, most likely tomorrow

**Comment by DrDaveD** [comment]
FIxed in #66 and #72.

**Comment by anderbubble** [comment]
Thanks, @DrDaveD! Sorry for the drive-by bug report: I was just quite confused during my first apptainer experience because I was trying to use "library://" and only by chance did I discover the information about library and shub. Just trying to help people who come after me to have fewer dead-ends to get caught in. ^_^

**Comment by DrDaveD** [comment]
No problem, thanks for caring.  You happen to catch it at a time just before we were about to update the documentation.  Even so I think there will be quite a few people who get tripped by it.
