### ISSUE TITLE
Fix epub output (I had to steal makefile from admindocs!)

### ISSUE THREAD

**Issue by symgryph** [apptainer/apptainer-userdocs#82]
## Which Document page:

UserDoc page

### Expected results:

Successful compile of the epub format

### Actual results:

System complains of 'mconfig' being missing. Only way to fix was to copy the 'working' makefile from admin docs, and type 
```bash
make epub
```

**Comment by symgryph** [comment]
Probably need to add the following to the readme:
git submodule init
git submodule update
make epub

**Comment by symgryph** [comment]
still get 'unknown command mconfig' after this. alas.

**Comment by DrDaveD** [comment]
Good point, that should be in the README.  Would you mind submitting a PR?  

From a clean clone if I run those two submodule commands, apptainer_source/mconfig exists and imake epub successfully runs ./mconfig.  I'm not sure what's happening in your environment.  Perhaps you can provide some more details to reproduce.

**Comment by DrDaveD** [comment]
Note that the README does say to use `SKIPCLI=1` if you don't care about the CLI docs, and that if you don't set that you need the go environment set up.  It just doesn't say to do `git submodule init`.
